# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set maven version
      run: mvn versions:set -DnewVersion=${GITHUB_REF##*/}

    - name: Build with Maven
      run: mvn -B package -pl validify-core --file pom.xml

    - name: Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        fail_ci_if_error: true

    - name: SonarCloud scan
      run: mvn sonar:sonar
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -pl validify-core  -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
